[book]
title = "Decision Toolkit"
authors = ["Dariusz Depta <dariusz.depta@dsntk.io>"]
description = "The Decision Toolkit book."
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2021"

[output.html.fold]
enable = true
level = 0
